name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 13.0.0+13

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.0
  dio: ^5.0.0
  shared_preferences: ^2.0.0
  flutter_hooks: ^0.18.0
  lottie: ^3.0.0
  intl: ^0.19.0
  geolocator: ^14.0.2
  battery_plus: ^7.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  package_info_plus:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/logo.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700


  uses-material-design: true
